import { useEffect, useMemo, useRef, useState } from 'react';
import { AudioLines, Bookmark, BookOpen, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Menu, Moon, Pause, Play, Search, Settings2, SkipBack, SkipForward, Sparkles, Sun, Trash2, Upload, Volume2, X } from 'lucide-react';
import { extractFile, splitSentences, type Story } from '../core/document';

const speeds = [0.5, 0.75, 1, 1.1, 1.25, 1.5, 1.75, 2];
type BookmarkEntry = { id: string; name: string; chapterIndex: number; paragraphIndex: number };
const storyKey = (story: Story) => `psr-position-${story.sourceName}-${story.text.length}`;

export default function App() {
  const [story, setStory] = useState<Story | null>(null);
  const [chapterIndex, setChapterIndex] = useState(0); const [paragraphIndex, setParagraphIndex] = useState(0); const [sentenceIndex, setSentenceIndex] = useState(0);
  const [playing, setPlaying] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [speed, setSpeed] = useState(1); const [theme, setTheme] = useState<'light' | 'sepia' | 'dark'>('sepia');
  const [fontSize, setFontSize] = useState(19); const [follow, setFollow] = useState(true); const [drawer, setDrawer] = useState(false);
  const [settings, setSettings] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState('');
  const [bookmarks, setBookmarks] = useState<BookmarkEntry[]>([]); const [confirmClear, setConfirmClear] = useState(false); const [link, setLink] = useState('');
  const fileRef = useRef<HTMLInputElement>(null); const activeRef = useRef<HTMLParagraphElement>(null); const inputRef = useRef<HTMLInputElement>(null);
  const paragraphs = story?.chapters[chapterIndex]?.paragraphs ?? [];
  const sentences = splitSentences(paragraphs[paragraphIndex]?.text ?? '');
  const currentText = sentences[sentenceIndex] ?? '';
  const allParagraphs = useMemo(() => story?.chapters.flatMap((chapter, ci) => chapter.paragraphs.map((p, pi) => ({ ...p, chapterIndex: ci, paragraphIndex: pi, chapterTitle: chapter.title }))) ?? [], [story]);
  const results = useMemo(() => query.trim() ? allParagraphs.filter(p => p.text.toLowerCase().includes(query.toLowerCase())).slice(0, 30) : [], [query, allParagraphs]);

  useEffect(() => { if (follow && playing) activeRef.current?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }, [chapterIndex, paragraphIndex, follow, playing]);
  useEffect(() => { if (story) localStorage.setItem(storyKey(story), JSON.stringify({ chapterIndex, paragraphIndex })); }, [story, chapterIndex, paragraphIndex]);
  useEffect(() => { if (searchOpen) inputRef.current?.focus(); }, [searchOpen]);
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('microsoftConnected') !== '1') return;
    window.history.replaceState({}, '', window.location.pathname);
    setBusy(true);
    void fetch('/api/documents/pending').then(async response => {
      if (!response.ok) { const body = await response.json() as { error?: string }; throw new Error(body.error || 'We couldn’t open this shared document.'); }
      const name = decodeURIComponent(response.headers.get('X-Document-Name') || 'shared-story.txt');
      await onFile(new File([await response.blob()], name));
    }).catch(e => setError(e instanceof Error ? e.message : 'We couldn’t open this shared document.')).finally(() => setBusy(false));
  }, []);
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => {
      const el = event.target as HTMLElement; if (['INPUT', 'TEXTAREA', 'SELECT'].includes(el.tagName) || el.isContentEditable) return;
      if (event.code === 'Space') { event.preventDefault(); togglePlay(); } else if (event.key === 'ArrowLeft' && event.shiftKey) { event.preventDefault(); moveChapter(-1); } else if (event.key === 'ArrowRight' && event.shiftKey) { event.preventDefault(); moveChapter(1); } else if (event.key === 'ArrowLeft') moveParagraph(-1); else if (event.key === 'ArrowRight') moveParagraph(1); else if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setSearchOpen(true); } else if (event.key === 'Escape') { setSearchOpen(false); setSettings(false); setConfirmClear(false); setDrawer(false); }
    };
    window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey);
  });
  useEffect(() => {
    if (!playing || !currentText || !('speechSynthesis' in window)) return;
    const utterance = new SpeechSynthesisUtterance(currentText); utterance.rate = speed;
    utterance.onend = () => advanceSentence(); utterance.onerror = event => { if (event.error === 'canceled' || event.error === 'interrupted') return; setPlaying(false); setError('Speech playback was interrupted. Press play to try again.'); };
    window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance);
    return () => { window.speechSynthesis.cancel(); };
  }, [playing, chapterIndex, paragraphIndex, sentenceIndex, speed, story]);

  function advanceParagraph() {
    if (!story) return;
    if (paragraphIndex < paragraphs.length - 1) { setParagraphIndex(paragraphIndex + 1); setSentenceIndex(0); }
    else if (chapterIndex < story.chapters.length - 1) { setChapterIndex(chapterIndex + 1); setParagraphIndex(0); setSentenceIndex(0); }
    else { setPlaying(false); setError('You’ve reached the end of the story.'); }
  }
  function advanceSentence() { if (sentenceIndex < sentences.length - 1) setSentenceIndex(sentenceIndex + 1); else advanceParagraph(); }
  function togglePlay() { if (!story) return; setError(''); setPlaying(v => !v); }
  function moveParagraph(delta: number) { if (!story) return; setError(''); setPlaying(false); setSentenceIndex(0); if (delta > 0) advanceParagraph(); else if (paragraphIndex > 0) setParagraphIndex(paragraphIndex - 1); else if (chapterIndex > 0) { setChapterIndex(chapterIndex - 1); setParagraphIndex(story.chapters[chapterIndex - 1].paragraphs.length - 1); } }
  function moveChapter(delta: number) { if (!story) return; const next = Math.min(story.chapters.length - 1, Math.max(0, chapterIndex + delta)); setChapterIndex(next); setParagraphIndex(0); setSentenceIndex(0); setPlaying(false); setDrawer(false); }
  async function onFile(file?: File) { if (!file) return; setBusy(true); setError(''); try { const loaded = await extractFile(file); let resumed = { chapterIndex: 0, paragraphIndex: 0 }; try { const saved = localStorage.getItem(storyKey(loaded)); if (saved) resumed = JSON.parse(saved) as typeof resumed; } catch { localStorage.removeItem(storyKey(loaded)); } const safeChapter = Math.min(resumed.chapterIndex, loaded.chapters.length - 1); setStory(loaded); setChapterIndex(safeChapter); setParagraphIndex(Math.min(resumed.paragraphIndex, loaded.chapters[safeChapter].paragraphs.length - 1)); setSentenceIndex(0); setPlaying(false); setBookmarks([]); setDrawer(false); } catch (e) { setError(e instanceof Error ? e.message : 'We couldn’t open this document.'); } finally { setBusy(false); } }
  async function openLink() {
    setError(''); try {
      const url = new URL(link);
      if (url.protocol !== 'https:' || !['1drv.ms', 'onedrive.live.com', 'sharepoint.com'].some(host => url.hostname === host || url.hostname.endsWith(`.${host}`))) throw new Error('Paste an HTTPS OneDrive or SharePoint sharing link.');
      setBusy(true);
      const response = await fetch('/api/documents/shared', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url: url.href }) });
      if (response.status === 401) { window.location.assign('/api/auth/login'); return; }
      if (!response.ok) { const body = await response.json() as { error?: string }; throw new Error(body.error || 'We couldn’t open this shared document.'); }
      const name = decodeURIComponent(response.headers.get('X-Document-Name') || 'shared-story.txt');
      await onFile(new File([await response.blob()], name));
    } catch (e) { setError(e instanceof Error ? e.message : 'Enter a valid document link.'); } finally { setBusy(false); }
  }
  function clearStory() { if ('speechSynthesis' in window) window.speechSynthesis.cancel(); if (story) localStorage.removeItem(storyKey(story)); setStory(null); setPlaying(false); setChapterIndex(0); setParagraphIndex(0); setSentenceIndex(0); setBookmarks([]); setQuery(''); setConfirmClear(false); setError(''); }
  function addBookmark() { if (!story) return; const name = window.prompt('Name this bookmark', story.chapters[chapterIndex].title); if (name?.trim()) setBookmarks([...bookmarks, { id: crypto.randomUUID(), name: name.trim(), chapterIndex, paragraphIndex }]); }
  const changeResult = (ci: number, pi: number) => { setChapterIndex(ci); setParagraphIndex(pi); setSentenceIndex(0); setPlaying(false); setSearchOpen(false); };

  return <div className={`app theme-${theme}`}>
    <header className="topbar"><a className="brand" href="#home" onClick={e => { e.preventDefault(); clearStory(); }} aria-label="Private Story Reader home"><span className="brand-mark"><AudioLines size={19}/></span><span>still<span className="brand-dot">.</span></span></a>
      <div className="topbar-center">{story ? <><span className="now-reading">NOW READING</span><span className="top-title">{story.title}</span></> : <span className="privacy-note"><span className="privacy-dot"/> PRIVATE BY DESIGN</span>}</div>
      <div className="top-actions">{story && <button className="icon-button desktop-only" onClick={() => setSearchOpen(true)} aria-label="Search story"><Search size={18}/></button>}<button className="icon-button" onClick={() => setSettings(true)} aria-label="Reader settings"><Settings2 size={19}/></button>{story && <button className="icon-button mobile-menu" onClick={() => setDrawer(true)} aria-label="Open chapters"><Menu size={20}/></button>}</div>
    </header>

    {!story ? <main id="home" className="landing"><section className="hero-copy"><div className="eyebrow"><span className="eyebrow-line"/> YOUR OWN LITTLE LISTENING ROOM</div><h1>Let the story<br/>find its <em>voice.</em></h1><p className="hero-subtitle">A quiet place to turn the words you love into something you can listen to.</p>
      <div className="import-card"><form onSubmit={e => { e.preventDefault(); void openLink(); }}><label className="field-label" htmlFor="story-link">A link to your story</label><div className="link-field"><input id="story-link" value={link} onChange={e => setLink(e.target.value)} placeholder="Paste a OneDrive or SharePoint link"/><button type="submit" disabled={!link.trim() || busy} aria-label="Open story from link"><ChevronRight size={20}/></button></div></form><div className="or-row"><span/> <span>OR BRING A FILE</span> <span/></div><button className="upload-drop" onClick={() => fileRef.current?.click()} disabled={busy}><span className="upload-icon">{busy ? <span className="spinner"/> : <Upload size={18}/>}</span><span><strong>{busy ? 'Opening your story…' : 'Choose a file to listen to'}</strong><small>Drop it here or browse your device</small></span><ChevronRight size={17} className="upload-arrow"/></button><input ref={fileRef} type="file" hidden accept=".txt,.md,.markdown,.pdf,.docx,.epub" onChange={e => void onFile(e.target.files?.[0])}/><div className="format-row"><span>TXT</span><span>MD</span><span>PDF</span><span>DOCX</span><span>EPUB</span><span className="size-note">UP TO 40 MB</span></div></div>
      <p className={`error-message ${error ? 'visible' : ''}`} role="status">{error}</p><div className="privacy-foot"><span className="lock-dot">⌑</span><span>Your story is processed in this browser and isn’t publicly shared.<br/><b>Clear your session whenever you’re ready.</b></span></div>
      </section><aside className="hero-art" aria-hidden="true"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="book-glow"/><div className="book-cover"><div className="book-cover-inner"><span className="cover-overline">A STORY, HELD CLOSE</span><div className="cover-art"><div className="cover-sun"/><div className="cover-hill hill-back"/><div className="cover-hill hill-front"/><div className="cover-path"/></div><span className="cover-title">somewhere<br/><i>between</i><br/>the words</span><span className="cover-rule"/><span className="cover-author">A MOMENT OF YOUR OWN</span></div></div><span className="floating-note note-top"><Sparkles size={14}/> MADE FOR SLOW MOMENTS</span><span className="floating-note note-bottom"><span className="sound-bars"><i/><i/><i/><i/><i/></span> YOUR VOICE. YOUR PACE.</span><div className="art-caption"><div className="caption-line"/><span>MAKE SPACE<br/>FOR A GOOD STORY</span></div></aside><div className="landing-bottom"><span>LISTEN A LITTLE CLOSER</span><span>LOCAL FIRST <i/> NO ACCOUNT NEEDED</span></div></main> : <main className="reader-shell">
      <aside className={`sidebar ${drawer ? 'sidebar-open' : ''}`}><div className="sidebar-head"><div className="sidebar-kicker">YOUR STORY</div><button className="icon-button close-drawer" onClick={() => setDrawer(false)} aria-label="Close chapters"><X size={18}/></button><h2>{story.title}</h2><div className="story-meta"><BookOpen size={14}/>{story.chapters.length} {story.chapters.length === 1 ? 'section' : 'chapters'}<span className="meta-dot"/>{allParagraphs.length} paragraphs</div></div><div className="sidebar-label">CONTENTS <span>{String(story.chapters.length).padStart(2, '0')}</span></div><nav className="chapter-list" aria-label="Story chapters">{story.chapters.map((chapter, i) => <button key={chapter.id} className={`chapter-link ${chapterIndex === i ? 'active' : ''}`} onClick={() => moveChapter(i - chapterIndex)}><span className="chapter-number">{String(i + 1).padStart(2, '0')}</span><span className="chapter-label">{chapter.title}</span>{chapterIndex === i && <span className="playing-indicator"><i/><i/><i/></span>}</button>)}</nav>{bookmarks.length > 0 && <><div className="sidebar-label bookmark-label">BOOKMARKS <span>{bookmarks.length}</span></div><div className="bookmark-list">{bookmarks.map(b => <button key={b.id} className="bookmark-row" onClick={() => changeResult(b.chapterIndex, b.paragraphIndex)}><Bookmark size={13}/><span>{b.name}</span><small>{b.chapterIndex + 1}:{b.paragraphIndex + 1}</small></button>)}</div></>}<div className="sidebar-bottom"><div className="follow-row"><span><span className="follow-icon"><AudioLines size={14}/></span> Follow narration</span><button role="switch" aria-checked={follow} className={`switch ${follow ? 'switch-on' : ''}`} onClick={() => setFollow(!follow)} aria-label="Follow narration"><i/></button></div><button className="clear-link" onClick={() => setConfirmClear(true)}><Trash2 size={14}/> Forget this story</button></div></aside>
      <section className="reading-pane"><div className="reader-toolbar"><div className="crumb"><span>YOUR LIBRARY</span><ChevronRight size={13}/><b>{story.title}</b></div><div className="reader-tools"><button className="reader-tool" onClick={addBookmark}><Bookmark size={15}/><span>Bookmark</span></button><button className="reader-tool" onClick={() => setSearchOpen(true)}><Search size={15}/><span>Find in story</span></button></div></div><article className="story-content" style={{ '--reading-size': `${fontSize}px` } as React.CSSProperties}><div className="chapter-overline"><span>CHAPTER {String(chapterIndex + 1).padStart(2, '0')}</span><i/></div><h1>{story.chapters[chapterIndex].title}</h1><div className="chapter-rule"><span/></div><div className="paragraphs">{paragraphs.map((p, i) => <p key={p.id} ref={i === paragraphIndex ? activeRef : null} className={`${i === paragraphIndex ? 'paragraph-current' : ''} ${playing && i === paragraphIndex ? 'sentence-active' : ''}`}>{splitSentences(p.text).map((sentence, j) => <span key={`${p.id}-s${j}`} className={i === paragraphIndex && j === sentenceIndex ? 'spoken-sentence' : ''}>{sentence}{j < splitSentences(p.text).length - 1 ? ' ' : ''}</span>)}</p>)}</div><div className="chapter-end"><span/> <span>END OF {chapterIndex === story.chapters.length - 1 ? 'STORY' : 'CHAPTER'}</span> <span/></div><div className="chapter-navigation"><button onClick={() => moveChapter(-1)} disabled={chapterIndex === 0}><ChevronLeft size={15}/> Previous chapter</button><span>{chapterIndex + 1} / {story.chapters.length}</span><button onClick={() => moveChapter(1)} disabled={chapterIndex === story.chapters.length - 1}>Next chapter <ChevronRight size={15}/></button></div></article></section>
    </main>}

    {story && <footer className="player"><div className="player-book"><div className="mini-cover"><BookOpen size={16}/></div><div className="player-book-copy"><strong>{story.title}</strong><span>{story.chapters[chapterIndex].title}</span></div></div><div className="player-center"><div className="transport"><button className="transport-secondary" onClick={() => moveParagraph(-1)} aria-label="Previous paragraph"><SkipBack size={17}/></button><button className="seek-button" onClick={() => moveParagraph(-1)} aria-label="Back 15 seconds"><span>15</span><SkipBack size={21}/></button><button className="play-button" onClick={togglePlay} aria-label={playing ? 'Pause' : 'Play'}>{playing ? <Pause size={20} fill="currentColor"/> : <Play size={20} fill="currentColor"/>}</button><button className="seek-button" onClick={() => moveParagraph(1)} aria-label="Forward 30 seconds"><SkipForward size={21}/><span>30</span></button><button className="transport-secondary" onClick={() => moveParagraph(1)} aria-label="Next paragraph"><SkipForward size={17}/></button></div><div className="progress-row"><span>{chapterIndex + 1}:{String(paragraphIndex + 1).padStart(2, '0')}</span><div className="progress-track"><div style={{ width: `${Math.round((allParagraphs.findIndex(p => p.chapterIndex === chapterIndex && p.paragraphIndex === paragraphIndex) + 1) / Math.max(allParagraphs.length, 1) * 100)}%` }}/></div><span>{allParagraphs.length} sections</span></div></div><div className="player-settings"><label className="speed-select"><span>PACE</span><select value={speed} onChange={e => setSpeed(Number(e.target.value))} aria-label="Speaking speed">{speeds.map(s => <option key={s} value={s}>{s.toFixed(s % 1 ? 2 : 1)}×</option>)}</select><ChevronDown size={12}/></label><div className="voice-note"><Volume2 size={15}/><span>Browser voice</span></div></div></footer>}

    {settings && <div className="overlay" onMouseDown={e => { if (e.target === e.currentTarget) setSettings(false); }}><section className="settings-panel" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div className="dialog-head"><div><span className="dialog-kicker">MAKE IT YOURS</span><h2 id="settings-title">Reading settings</h2></div><button className="icon-button" onClick={() => setSettings(false)} aria-label="Close settings"><X size={19}/></button></div><div className="setting-section"><h3>Appearance</h3><div className="setting-row"><div><strong>Reading theme</strong><small>Choose a comfortable page color</small></div><div className="theme-options">{(['light', 'sepia', 'dark'] as const).map(t => <button key={t} onClick={() => setTheme(t)} className={theme === t ? 'theme-choice chosen' : 'theme-choice'} aria-pressed={theme === t}>{t === 'light' ? <Sun size={14}/> : t === 'dark' ? <Moon size={14}/> : <span className="sepia-dot"/>}{t[0].toUpperCase() + t.slice(1)}</button>)}</div></div><div className="setting-row"><div><strong>Text size</strong><small>Adjust the reading type</small></div><div className="font-controls"><button onClick={() => setFontSize(Math.max(16, fontSize - 1))} aria-label="Decrease text size">A−</button><span>{fontSize}px</span><button onClick={() => setFontSize(Math.min(25, fontSize + 1))} aria-label="Increase text size">A+</button></div></div></div><div className="setting-section"><h3>Listening</h3><div className="setting-row"><div><strong>Speaking pace</strong><small>Change narration speed</small></div><select className="setting-select" value={speed} onChange={e => setSpeed(Number(e.target.value))}>{speeds.map(s => <option key={s} value={s}>{s.toFixed(s % 1 ? 2 : 1)}×</option>)}</select></div><div className="setting-row"><div><strong>Follow narration</strong><small>Keep the current paragraph in view</small></div><button role="switch" aria-checked={follow} className={`switch ${follow ? 'switch-on' : ''}`} onClick={() => setFollow(!follow)}><i/></button></div></div><div className="privacy-card"><span><CircleHelp size={17}/></span><p><strong>Your story stays in this browser.</strong><br/>Speech uses the voice available on your device. Story text isn’t uploaded by this app.</p></div><div className="dialog-footer"><button className="secondary-button" onClick={() => { setSettings(false); setConfirmClear(true); }}><Trash2 size={14}/> Forget story</button><button className="primary-button" onClick={() => setSettings(false)}>Done <Check size={15}/></button></div></section></div>}
    {searchOpen && <div className="overlay" onMouseDown={e => { if (e.target === e.currentTarget) setSearchOpen(false); }}><section className="search-panel" role="dialog" aria-modal="true" aria-labelledby="search-title"><div className="search-head"><div className="search-box"><Search size={19}/><input ref={inputRef} id="search-title" value={query} onChange={e => setQuery(e.target.value)} placeholder="Find a word or phrase…"/><kbd>ESC</kbd></div><button className="icon-button" onClick={() => setSearchOpen(false)} aria-label="Close search"><X size={19}/></button></div><div className="search-results">{!query.trim() ? <div className="search-empty"><Search size={20}/><span>Search through this story</span><small>Your search stays on this device.</small></div> : results.length ? results.map(result => <button className="search-result" key={result.id} onClick={() => changeResult(result.chapterIndex, result.paragraphIndex)}><span>{result.chapterTitle}</span><p>{result.text.slice(0, 190)}{result.text.length > 190 ? '…' : ''}</p><ChevronRight size={15}/></button>) : <div className="search-empty"><span>No passages found</span><small>Try another word or phrase.</small></div>}</div><div className="search-foot">{query ? `${results.length} ${results.length === 1 ? 'passage' : 'passages'}${results.length === 30 ? ' (showing first 30)' : ''}` : 'Press Ctrl K any time to search'}</div></section></div>}
    {confirmClear && <div className="overlay" onMouseDown={e => { if (e.target === e.currentTarget) setConfirmClear(false); }}><section className="confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="clear-title"><div className="confirm-icon"><Trash2 size={20}/></div><h2 id="clear-title">Forget this story?</h2><p>The story text, playback position and bookmarks will be cleared from this browser. This can’t be undone.</p><div className="confirm-actions"><button className="secondary-button" onClick={() => setConfirmClear(false)}>Keep reading</button><button className="danger-button" onClick={clearStory}>Forget story</button></div></section></div>}
  </div>;
}
